[Feature/#3] search / 검색 뷰 구현
Keyneez/Keyneez-AOS-Release pull request #14
Opened 2023-04-13 08:37 UTC by 0zlrlo

## 관련 이슈
- closed #3 

## 작업 내역
- 기본적인 기능 구현
- 서버통신을 위한 기초 작업 완료

## PR 포인트

## 실행 화면

2023-04-17 14:45 UTC, b1urrrr requested changes
고생하셨습니다 ㅎㅎ

2023-04-17 14:45 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/search/SearchActivity.kt
> +            }
```suggestion
            if ((event.action == KeyEvent.ACTION_DOWN) && (keyCode == KeyEvent.KEYCODE_ENTER)) {
                // 뷰모델 통신하는 코드 작성하기
                true
                return
            }
            false
```

요런식으로 바꿔봐도 좋을 것 같아용

2023-04-17 14:45 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/search/SearchAdapter.kt
> +class SearchAdapter : RecyclerView.Adapter<SearchAdapter.getViewHolder>() {
ListAdapter로 바꿔주세요!

2023-04-17 14:45 UTC, b1urrrr commented on app/src/main/res/layout/item_search_content.xml
> +        <import type="android.view.View" />
이런 변수나 import문은 데이터바인딩을 사용하면서 필요할 때 그때그때 써주는 게 효율적일 것 같습니다!

2023-05-08 16:00 UTC, etama123 approved these changes
고생하셨습니다!~

2023-05-08 16:13 UTC, closed without merging