[UI/#17] 탐색 뷰 UI 작업
Keyneez/Keyneez-AOS-Release pull request #26
Opened 2023-05-08 16:00 UTC by 0zlrlo

## 관련 이슈
- closed #17

## 작업 내역
- 리사이클러뷰 구현
- 모션레이아웃으로 전체 틀 구현
- coordinator도 시도
- nestedlayout 시도했다가 철회

## PR 포인트
- 모션레이아웃 봐주시면 감사하겠습니다.
- 검색 뷰는 예전에 만들어 놓은 것 그대로입니다. 추후에 검색 뷰 완성된 것 pr로 올리겠습니다.
- 리사이클러뷰의 최하단과 밑 바닥 사이에 122dp 차이가 있는데 이걸 padding으로 해야 하는지 margin으로 줘야 하는지 궁금합니다.

## 실행 화면
<img width="292" alt="스크린샷 2023-05-09 오전 12 58 18" src="https://user-images.githubusercontent.com/99941493/236872048-a025c517-bb78-4903-a93a-b939e363aa68.png">

2023-05-08 17:38 UTC, b1urrrr requested changes
고생하셨습니다!
MotionLayout은 저도 사용해보지 않은 기술이라 리뷰 해드리기가 어렵습니다 🥲
같이 이것저것 많이 시도해봅시다

2023-05-08 17:38 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/data/model/response/ResponseGetSearchDto.kt
> +@kotlinx.serialization.Serializable
```suggestion
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
```

임포트로 좀 더 간략하게 써봅시다!

2023-05-08 17:38 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/data/model/response/ResponseGetSearchDto.kt
> +    val liked: Boolean
```suggestion
    @SerialName("liked")
    val liked: Boolean
```
앱 난독화에서 예외 상황들을 예방하기 위해서 모든 속성에 SerialName을 넣어주는 것이 좋다고 합니다!

2023-05-08 17:38 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/data/model/response/ResponseGetSearchDto.kt
> +data class ResponseGetSearchDto(
조금 더 구체적이어도 될 것 같은데 어떤가요?
```suggestion
data class ResponseGetSearchResultDto(
```

2023-05-08 17:38 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/search/SearchActivity.kt
> +    lateinit var searchAdapter: SearchAdapter
```suggestion
    private lateinit var searchAdapter: SearchAdapter
```
외부에서 사용하지 않는 멤버 필드는 `private`을 지정해주세요!

2023-05-08 17:38 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/search/SearchActivity.kt
> +    }
BindingActivity의 dispatchMotionEvent 메서드 내부에서 hideKeyboard를 호출하면 다른 클릭 리스너 없이도 일괄적으로 키보드를 숨기는 이벤트를 처리할 수 있습니다!

2023-05-08 17:38 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/search/SearchActivity.kt
> +    }
```suggestion
    private fun initSearchBtnKeyListener() {
        binding.btnSearchResult.setOnKeyListener { v, keyCode, event ->
            if ((event.action == KeyEvent.ACTION_DOWN) && (keyCode == KeyEvent.KEYCODE_ENTER)) {
                // 뷰모델 통신하는 코드 작성하기
                true
                return@initSearchBtnKeyListener
            }
            false
        }
    }
```
더 섬세한 예외 처리와 가독성 개선을 위해 `else` 사용은 지양해주세요!
한번 early return 패턴에 대해 찾아보셔도 좋을 것 같습니다 :)

2023-05-08 17:38 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/search/SearchActivity.kt
> +    }
그리고 이 함수는 클릭 리스너가 아닌 키 리스너를 설정하는 함수이므로 역할에 맞는 네이밍을 하는 것이 좋을 것 같습니다!

2023-05-08 17:38 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/search/SearchActivity.kt
> +    }
```suggestion
    private fun initBackBtnClickListener() {
        binding.btnSearchBack.setOnSingleClickListener {
            finish()
        }
    }
```
이미 Search Activity 내부에 포함된 메서드이므로 search는 명시하지 않아도 될 것 같습니다!

2023-05-08 17:38 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/search/SearchAdapter.kt
> +class SearchAdapter : RecyclerView.Adapter<SearchAdapter.getViewHolder>() {
효율적으로 Item의 갱신을 처리할 수 있는 ListAdapter로 구현해주세요!

2023-05-08 17:38 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/search/SearchAdapter.kt
> +//                ContextCompat.startActivity(binding.root.context, intent, null)
`// TODO: 처리해야하는 작업` 을 활용해서 명시해보셔도 좋을 것 같습니다!
이를 제외한 현재 실행에 불필요한 주석은 지우면 좋을 것 같아요

2023-05-08 17:38 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/search/SearchViewModel.kt
> +class SearchViewModel @Inject constructor() : ViewModel()
나중에 사용하겠지만 서버 통신을 구현하지 않은 현재는 불필요한 파일로 보이긴 하네요

2023-05-08 17:38 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/search/SearchAdapter.kt
> +    var data = listOf<ResponseGetSearchDto>()
Dto(data > entity)는 서버통신에 활용되는 모든 속성이 포함된 데이터 클래스에 해당합니다. UI에서 사용되는 속성만 나타낸 데이터 클래스를 domain > model에 만들어 사용해봅시다! (Dto는 서버 통신 구현할 때 추가하면 좋을 것 같습니다)

2023-05-08 17:38 UTC, b1urrrr commented on app/src/main/res/drawable/ic_full_heart.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
`ic_heart_empty`, `ic_heart_fill` 는 어떨까요?
이전에 채워진 아이콘의 네이밍은 fill을 활용하기로 언급했었던 것 같습니다!

2023-05-08 17:38 UTC, b1urrrr commented on app/src/main/res/drawable/img_explore_background.png
혹시 어떤 확장자로 추출하셨나요?

2023-05-08 17:38 UTC, b1urrrr commented on app/src/main/res/layout/activity_explore.xml
> +<layout xmlns:android="http://schemas.android.com/apk/res/android"
```suggestion
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
```

2023-05-08 17:38 UTC, b1urrrr commented on app/src/main/res/layout/activity_explore.xml
> +            android:layout_width="match_parent"
ConstraintLayout의 내부 컴포넌트들은 match_parent가 아닌 0dp와 제약을 사용해주세요! MotionLayout 또한 ConstraintLayout의 하위 클래스에 해당합니다.

2023-05-08 17:38 UTC, b1urrrr commented on app/src/main/res/layout/activity_explore.xml
> +            style="@style/TextAppearance.Keyneez.HeadingSemibold20"
Material Design 을 적용한 pr 코리한 다음 바로 머지해주시고 풀받아서 명칭 통일해주세요! textAppearances 이름들을 축약해놨습니다 :)

2023-05-08 17:38 UTC, b1urrrr commented on app/src/main/res/layout/activity_explore.xml
> +            tools:ignore="SpeakableTextPresentCheck" />
요건 왜 추가하신 건가요?
이미지와 관련된 컴포넌트들은 content description을 추가해주세요!

2023-05-08 17:38 UTC, b1urrrr commented on app/src/main/res/layout/activity_explore.xml
> +            app:layout_constraintStart_toStartOf="@id/tv_explore_popular"
ViewPager2의 속성과 shape 파일을 활용하여 구현하는 것이 적합할 것 같습니다.

2023-05-08 17:38 UTC, b1urrrr commented on app/src/main/res/values/strings.xml
> +    //explore
```suggestion
    <!-- explore -->
```
이렇게 써보는 건 어떨까요?

2023-05-08 17:38 UTC, b1urrrr commented on app/src/main/res/xml/motion_explore.xml
> +<?xml version="1.0" encoding="utf-8"?>
explore의 어떤 뷰에 대한 모션 xml인지 좀 더 명시적으로 네이밍을 해주시면 좋을 것 같습니다!

2023-05-08 17:40 UTC, b1urrrr commented
> 리사이클러뷰의 최하단과 밑 바닥 사이에 122dp 차이가 있는데 이걸 padding으로 해야 하는지 margin으로 줘야 하는지 궁금합니다.

어떤 컴포넌트를 기준으로 하느냐에 따라 다를 것 같은데, scrollbar가 자연스럽게 보여지는 방향으로 구현해주시면 될 것 같습니다!

2023-05-09 01:31 UTC, 0zlrlo commented on app/src/main/java/com/release/keyneez/data/model/response/ResponseGetSearchDto.kt
> +data class ResponseGetSearchDto(
너무 네이밍이 길어지는 것 같아서 머뭇거렸는데 말씀하신대로 수정하도록 하겠습니다!

2023-05-09 04:43 UTC, b1urrrr requested changes
어제 새벽에 너무 심신미약 상태였어서 xml 부분만 다시 봤습니다!
xml 코드에서도 항상 code reformat 단축키를 눌러주세요!

2023-05-09 04:43 UTC, b1urrrr commented on app/src/main/res/layout/activity_explore.xml
> +            app:layout_constraintTop_toTopOf="parent" />
이건 왜 이미지뷰인가요? 무슨 컴포넌트인지 잘 모르겠습니다!

2023-05-09 04:43 UTC, b1urrrr commented on app/src/main/res/layout/activity_explore.xml
> +            app:autoSizeTextType="uniform"
요건 무슨 속성인가요?

2023-05-09 04:43 UTC, b1urrrr commented on app/src/main/res/layout/activity_explore.xml
> +            app:layout_constraintTop_toTopOf="parent" />
참고로 툴바는 Toolbar라는 컴포넌트가 따로 존재합니당

2023-05-09 04:43 UTC, b1urrrr commented on app/src/main/res/layout/activity_explore.xml
> +            style="@style/TextAppearance.Keyneez.HeadingSemibold20"
그러고보니 뷰 페이저와 리사이클러뷰 구현이 안 되어 있는 것 같습니다!

2023-05-09 04:43 UTC, b1urrrr commented on app/src/main/res/layout/activity_explore.xml
> +            android:id="@+id/tv_explore_entire"
```suggestion
            android:id="@+id/tv_explore_all"
```
보통 앱에서 전체를 뜻할 때는 all을 많이 쓰는 것 같은데 어떤가요?

2023-05-09 04:43 UTC, b1urrrr commented on app/src/main/res/layout/activity_search.xml
>          android:id="@+id/layout_search_result"
이 레이아웃에는 검색하는 부분도 포함되어 있어서 result를 빼는 게 어떤가요?
```suggestion
        android:id="@+id/layout_search"
```

2023-05-09 04:43 UTC, b1urrrr commented on app/src/main/res/layout/item_explore_content.xml
> +            android:layout_marginEnd="15dp"
```suggestion
            android:layout_marginHorizontal="15dp"
            android:layout_marginTop="4dp"
```

발견~

2023-05-09 04:43 UTC, b1urrrr commented on app/src/main/res/layout/item_explore_content.xml
> +            android:layout_marginEnd="27dp"
```suggestion
            android:layout_marginHorizontal="28dp"
```
같은 값을 주는 게 적합할 것 같습니다

2023-05-09 04:43 UTC, b1urrrr commented on app/src/main/res/layout/item_search_content.xml
> +            type="com.release.keyneez.data.model.response.ResponseGetSearchDto" />
나중에 사용되겠지만 data가 필요할 때 넣어주셨으면 좋겠어요!
현재로만 봐서는 사용되지 않는 불필요한 변수라는 생각이 들어요

2023-05-09 10:39 UTC, 0zlrlo commented on app/src/main/java/com/release/keyneez/presentation/main/search/SearchActivity.kt
> +    }
엇 그 저희 컨벤션에 없는데 어떤 이름으로 하는 것이 좋을까요?

2023-05-09 10:40 UTC, 0zlrlo commented on app/src/main/java/com/release/keyneez/presentation/main/search/SearchAdapter.kt
> +class SearchAdapter : RecyclerView.Adapter<SearchAdapter.getViewHolder>() {
넵 이건 추후에 search 관련한 작업을 처리할 때 하도록 하겠습니다

2023-05-09 10:58 UTC, 0zlrlo commented on app/src/main/res/drawable/img_explore_background.png
리사이클러뷰 안에 있는 동그라미 배경입니다! svg로 추출하려니까 안되더라고요,,

2023-05-09 11:18 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/search/SearchActivity.kt
> +    }
![image](https://github.com/Keyneez/Keyneez-AOS-Release/assets/70993562/5f3a05c9-f3fd-4555-b59e-1337140a049e)

클릭 리스너는 초기화 함수 예시 중 하나라고 생각하시면 될 것 같아요! 키 리스너로 네이밍하는 게 좋을 것 같슴다 :)

2023-05-09 11:20 UTC, b1urrrr commented on app/src/main/res/drawable/img_explore_background.png
png인가요?

2023-05-10 09:27 UTC, 0zlrlo commented on app/src/main/res/layout/activity_explore.xml
> +            app:autoSizeTextType="uniform"
motionLayout과 관련된 것입니다! 스크롤하게 되면 텍스트가 작아져야 하는데 그것과 관련된 속성이라고 알고 있습니다.

2023-05-10 09:28 UTC, 0zlrlo commented on app/src/main/res/layout/activity_explore.xml
> +            app:layout_constraintTop_toTopOf="parent" />
찾아보니 툴바 역할을 하는 전체 부분을 따로 툴바로 쓰지 않고 보통 imageview로 두더라고요..! 저는 여기 부분을 constraintlayout으로 하고자 했는데 여러 코드들을 보니 그렇지 않은 거 같아 저도 전체 background를 이미지뷰로 두었습니다.

2023-05-10 10:14 UTC, 0zlrlo commented on app/src/main/res/layout/activity_explore.xml
> +            tools:ignore="SpeakableTextPresentCheck" />
No speakable text present 경고를 해결하기 위한 코드입니다

2023-05-10 10:23 UTC, b1urrrr commented on app/src/main/res/layout/activity_explore.xml
> +            app:layout_constraintTop_toTopOf="parent" />
처음 알게 되는 사실이네요! 참고하신 코드들 공유해주실 수 있나요?

2023-05-10 10:25 UTC, b1urrrr commented on app/src/main/res/layout/activity_explore.xml
> +            tools:ignore="SpeakableTextPresentCheck" />
content description 설정 후 속성 제거해주시면 좋을 것 같습니다!

2023-05-10 11:06 UTC, 0zlrlo commented on app/src/main/res/layout/activity_explore.xml
> +            app:layout_constraintTop_toTopOf="parent" />
엇 네 제가 추후에 모션레이아웃 작업할 때 공유하겠습니다!

2023-05-18 16:43 UTC, b1urrrr requested changes
앞 부분만 일단 코리 해봤습니다!
pull 받고 충돌 해결해주신 다음에 다시 rerequest 부탁드립니다 💖

2023-05-18 16:43 UTC, b1urrrr commented on app/build.gradle
> +    }
위에 이미 뷰바인딩 설정이 되어 있어서 제거하셔도 될 것 같아요!

2023-05-18 16:43 UTC, b1urrrr commented on app/build.gradle
> +    implementation 'androidx.constraintlayout:constraintlayout:2.0.0-beta1'
요 속성도 아래에 기본으로 종속성이 추가되어 있어서 제거해주시면 좋을 것 같아요 :)

2023-05-18 16:43 UTC, b1urrrr commented on app/build.gradle
> +    implementation 'com.google.android.material:material:1.7.0'
material도 이미 추가되어 있습니다!

2023-05-18 16:43 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/domain/model/ExploreData.kt
> +)
크 도메인 데이터 클래스까지 나눠놓으셨네요 👍👍

2023-05-18 16:43 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/explore/ExploreAdapter.kt
> +}
`getItemCount`와 `createFragment`는 리스트를 활용하여 구현하는 것이 가독성이나 유지보수에 좋을 것 같습니다!
FragmentStateAdapter는 처음 보는데 어떤 경우에 사용하는 어댑터인가요?

2023-05-18 16:43 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/explore/ExploreFragment.kt
> +    }
```suggestion
    private fun initExploreViewPagerAdapter() {
        with (binding) {
            val exploreTabTitles = listOf(
                getString(R.string.explore_popular),
                getString(R.string.explore_recent)
            )

            vpExplore.adapter = ExploreAdapter(parentFragmentManager, lifecycle)

            TabLayoutMediator(tabExplore, vpExplore) { tab, position ->
                tab.text = exploreTabTitles[position]
            }.attach()
        }
    }
```
`with` 키워드를 활용하는 것이 더 코틀린 언어를 잘 활용한 처리라고 생각합니다!
이 기회에 scope function에 대해 공부해보셔도 좋을 것 같아요 :)

2023-05-18 16:43 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/explore/ExploreFragment.kt
> +        }
```suggestion
        binding.btnExploreSearch.setOnSingleClickListener {
            startActivity(Intent(activity, SearchActivity::class.java))
        }
```
한 줄로 쓰는 것이 더 깔끔한 것 같습니다!
그리고 `activity`를 통해 더 간결하게 `getActivity()`를 호출할 수 있습니다

2023-05-18 18:14 UTC, b1urrrr requested changes
고생 많으셨습니다 🥹💖
동영상을 녹화해주시거나 에뮬레이터에 gif 녹화 기능이 있는데 이를 활용해서 pr 실행 화면에 첨부해주시면 xml도 좀 더 꼼꼼하게 봐드릴 수 있을 것 같습니다!

2023-05-18 18:14 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/explore/ExploreFragment.kt
> +        }
```suggestion
        @JvmStatic
        fun newInstance() = ExploreFragment()
```
companion object 내부의 메서드에는 `@JvmStatic`을 붙이는 것이 컴파일 시 코드 복잡도를 줄일 수 있다고 합니다! 다른 프래그먼트에도 붙여주세요!
그리고 Single Expression 함수로 작성하는 것이 깔끔할 것 같습니당

2023-05-18 18:14 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/explore/popular/PopularAdapter.kt
> +            binding.root.setOnClickListener {}
```suggestion
            with (binding) {
                ivExploreBackground.load(item.background)
                tvExploreCategory.text = item.category
                tvExploreContentTitle.text = item.title
                tvExploreDate.text = item.date
                // TODO : root.setOnSingleClickListener 구현
            }
```
여기도 `with` 키워드를 사용하면 더 간결하게 작성할 수 있는데, 그냥 데이터바인딩을 적용시켜주셨으면 좋겠습니다!
그리고 보완이 필요한 부분은 주석을 붙여주시는 게 추후 개발에 도움이 될 것 같습니다

2023-05-18 18:14 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/domain/model/ExploreData.kt
> +)
크 도메인 데이터 클래스까지 나눠놓으셨네요 👍👍
피그마를 확인해보니 이 데이터 클래스는 전역에서 재활용될 것 같습니다. 따라서 클래스명을 Activity(활동)으로 바꾸는 건 어떨까요?

2023-05-18 18:14 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/data/entity/response/ResponseGetSearchResultDto.kt
> +    @SerialName("liked") val liked: Boolean
dto에서는 contentKey, contentTitle, contentImg가 더 직관적일 것 같은데 어떻게 생각하시나요?

2023-05-18 18:14 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/explore/popular/PopularViewModel.kt
> +    private fun getPopularItemList() {
```suggestion
    private fun getPopularActivityList() {
```
Item 이라는 단어가 모호한 것 같습니다!

2023-05-18 18:14 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/explore/recent/RecentFragment.kt
> +    val data = mutableListOf<ExploreData>()
이건 언제 쓰이는 변수인가요?

2023-05-18 18:14 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/explore/recent/RecentAdapter.kt
> +        }
요기도 PopularAdapter와 마찬가지입니다!

2023-05-18 18:14 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/explore/recent/RecentFragment.kt
> +    private lateinit var RecentAdapter: RecentAdapter
Adapter 또한 프래그먼트 뷰에 종속되는 리소스이기 때문에 `onDestroyView`에서 `null`로 해제해주는 것이 메모리 누수를 방지할 수 있습니다! [제 과제 레포의 HomeFragment](https://github.com/GO-SOPT-ANDROID/chaeyeon-jeon/blob/d24ff8c3316c3c6c358462e7f936473b9adb7b64/app/src/main/java/org/android/go/sopt/presentation/main/home/HomeFragment.kt#LL52C32-L52C32)를 참고해주시면 좋을 것 같습니다 :)

2023-05-18 18:14 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/explore/recent/RecentFragment.kt
> +        }
```suggestion
        viewModel.activityList.observe(viewLifecycleOwner) { activityList ->
            recentAdapter.data = activityList
            recentAdapter.notifyDataSetChanged()
        }
```
요기도 item이라는 명칭 보다는 activity를 사용하면 좋을 것 같구, `it` 보다는 어떤 변수인지 명시해주는 것이 보기 좋을 것 같습니다!
(ListAdapter와 관련된 리뷰는 일단 생략하겠습니다! 나중에 꼭 바꿔주셔야해요... 🥹)

2023-05-18 18:14 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/explore/recent/RecentFragment.kt
> +    private lateinit var RecentAdapter: RecentAdapter
```suggestion
    private lateinit var recentAdapter: RecentAdapter
```
그리구 깜빡하신 것 같긴 하지만 상수가 아닌 일반 변수는 lowerCamelCase로 작성하는 것이 [공식문서에서 안내하고 있는 관례](https://developer.android.com/kotlin/style-guide#non-constant_names)입니다!

2023-05-18 18:14 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/explore/recent/RecentFragment.kt
> +        initRecentAdapter()
초기화를 먼저 수행하도록 함수 순서를 바꿔주는 것이 좋을 것 같습니다!
그리고 여기도 Data라는 명칭보다는 Activity를 사용하는 것이 직관적일 것 같습니다!

2023-05-18 18:14 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/explore/recent/RecentViewModel.kt
> +    private fun getRecentItemList() {
```suggestion
    private val _activityList = MutableLiveData<List<ExploreData>>()
    val activityList: LiveData<List<ExploreData>>
        get() = _activityList

    init {
        getRecentActivityList()
    }

    private fun getRecentActivityList() {
```
요기도 마찬가지로 직관적인 명칭~
다른 코드에서도 바꿀만한 네이밍이 있는지 한번씩 확인해주세요!

2023-05-18 18:14 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/search/SearchActivity.kt
> +    }
전에도 드린 리뷰인데 BindingActivity에서 dispatchTouchEvent를 활용하면 일괄적으로 키보드 숨기기 처리가 가능합니다! 잘 이해가 안 가신다면 일단 제거해주세요!

2023-05-18 18:14 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/search/SearchAdapter.kt
> +            binding.root.setOnClickListener {
```suggestion
            binding.root.setOnSingleClickListener {
```
아직 제대로 구현 안 하신 것 같지만 SingleClickListener를 사용해주세요!

2023-05-18 18:14 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/search/SearchViewModel.kt
> +class SearchViewModel @Inject constructor() : ViewModel()
일단 코드를 적어놓기보다는 왜 필요한 코드인지 생각해보고, 필요할 때 구현해보는 습관이 생기면 코드에 대한 이해가 빨라지실 겁니다! 다음부터 그런 식으로 해보는 걸 강추드려요!!!

2023-05-18 18:14 UTC, b1urrrr commented on app/src/main/res/drawable/img_explore_background.png
이거 제가 놓쳤었네요! png 파일은 픽셀로 이루어진 사진이기 때문에 화면 기기에 따라 이미지가 깨져 보일 수 있는 단점이 존재합니다. 아래는 svg 파일이 제공되지 않았을 때 대처하는 방법입니다
1. 디자이너 분께 벡터 처리가 된 svg 파일을 요청합니다.
2. 벡터 처리가 어렵다면 dpi 별로 png를 받아 안드로이드 스튜디오에 dpi 별로 이미지를 저장합니다.

2023-05-18 18:14 UTC, b1urrrr commented on app/src/main/res/drawable/sel_search_heart.xml
[이번에 type을 명시하도록 변경된 selector 컨벤션](https://www.notion.so/drawable-file-name-c041787576234524909069e1b5f9baf4) 한번 확인 부탁드립니다!

EX) sel_search_drawable_heart

2023-05-18 18:14 UTC, b1urrrr commented on app/src/main/res/layout/fragment_explore.xml
> +        android:id="@+id/layout_explore_entire"
`layout_explore`로 해도 충분할 것 같습니다!

2023-05-18 18:14 UTC, b1urrrr commented on app/src/main/res/layout/fragment_explore.xml
> +            app:layout_constraintTop_toTopOf="parent" />
ConstraintLayout 내부 컴포넌트는 0dp를 사용해봅시다!

2023-05-18 18:14 UTC, b1urrrr commented on app/src/main/res/layout/fragment_explore.xml
> +            android:contentDescription="@string/explore_search_contentdescription"
크 좋아요 👍👍

2023-05-18 18:14 UTC, b1urrrr commented on app/src/main/res/layout/fragment_explore.xml
> +            app:tabIndicatorHeight="1.8dp"
소수점은 반올림합시다!

2023-05-18 18:14 UTC, b1urrrr commented on app/src/main/res/layout/fragment_explore.xml
> +            android:layout_height="45dp"
요기 고정 dp로 높이를 지정하신 이유가 있으신가요?

2023-05-18 18:14 UTC, b1urrrr commented on app/src/main/res/layout/fragment_explore.xml
> +            app:tabTextAppearance="@style/SubtitleSemibold18"
```suggestion
            style="@style/SubtitleSemibold18"
```
style 속성 사용해주시는 게 맞습니다! 다른 부분도 수정해주세요 🤣

2023-05-18 18:14 UTC, b1urrrr commented on gradle.properties
> +>>>>>>> fd9c19eff6a4894d2162cefd4c647792fca664f4
충돌 해결이 안 되어 있는 것 같습니다!
추가된 속성들은 무슨 속성인가요?

2023-05-19 02:12 UTC, 0zlrlo commented on app/src/main/java/com/release/keyneez/presentation/main/explore/ExploreAdapter.kt
> +}
뷰페이저가 제공하는 어댑터 클래스입니다! 각 페이지를 프래그먼트로 구성하고 싶을 때 사용하는 어댑터로 저 또한 그런 방식으로 사용하기에 사용하였습니다. 리스트를 활용한다는 말이 어떤 것인가요?

2023-05-19 02:50 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/explore/ExploreAdapter.kt
> +}
https://github.com/Keyneez/Keyneez-AOS/blob/develop/app/src/main/java/com/keyneez/presentation/login/LoginAdapter.kt 코드 참고 해주세요
잊고 있었는데 이전 리포에서 FragmentStateAdapter 사용했었네요

2023-05-19 12:38 UTC, 0zlrlo commented on app/src/main/java/com/release/keyneez/presentation/main/explore/ExploreAdapter.kt
> +}
공부하면서 고치고 보니까 컴파일 에러가 떠서 뭔가 봤더니 FragmentStateAdapter requires a FragmentManager and Lifecycle in its constructor. 라고 해서 다시 원래 코드로 고쳤습니다~.!

2023-05-19 13:02 UTC, 0zlrlo commented on app/src/main/java/com/release/keyneez/presentation/main/explore/recent/RecentFragment.kt
> +        }
넵! 코드 이것저것 짜다보니 까먹고 익숙한 방식으로 짰네요ㅠㅠ

2023-05-19 13:02 UTC, 0zlrlo commented on app/src/main/java/com/release/keyneez/presentation/main/explore/recent/RecentFragment.kt
> +    val data = mutableListOf<ExploreData>()
헉..안 쓰이는 거 같아 삭제했습니다.

2023-05-19 13:07 UTC, 0zlrlo commented on gradle.properties
> +>>>>>>> fd9c19eff6a4894d2162cefd4c647792fca664f4
엇 헉,,삭제를 안했네요! 모션레이아웃이었던 걸로 기억합니다!

2023-05-19 13:09 UTC, 0zlrlo commented on app/src/main/res/layout/fragment_explore.xml
> +            app:tabTextAppearance="@style/SubtitleSemibold18"
이건 tab바 속성 중 하나입니다! style로도 되나 싶어서 해 봤는데 그럴 경우 탭바에 텍스트가 적용이 안되어서 다시 기존 코드로 돌려 놓았습니다

2023-05-19 13:11 UTC, 0zlrlo commented on app/src/main/res/layout/fragment_explore.xml
> +            android:layout_height="45dp"
tablayout 자체적으로 높이가 있습니다! 근데 이를 무시하고 원하는 대로 크기를 하고 싶으면 따로 height의 크기를 지정해 주어야 된다는 글을 보아서 높이를 고정적으로 지정했습니다.

2023-05-19 13:13 UTC, 0zlrlo commented on app/src/main/res/layout/fragment_explore.xml
> +            app:layout_constraintTop_toTopOf="parent" />
모션레이아웃 때는 width의 높이를 지정하더라구요!ㅠㅠ 이것에 대해서는 제가 더 공부해 보겠습니다! 이 부분은 추후에 고치도록 하겠습니다.

2023-05-19 13:18 UTC, 0zlrlo commented on app/src/main/java/com/release/keyneez/presentation/main/search/SearchActivity.kt
> +    }
헉 아 제가 검색 관련한 코드는 그때도 남겼듯이 검색뷰 브랜치에서 한꺼번에 다 고치려고 하였습니다. 저번부터 검색 뷰와 관련된 코드 수정관련 리뷰 남긴 내용들은 제가 이슈 적는 곳에다가 다 적어 놓았습니다. 그때 고치도록 하겠습니다:)

2023-05-19 13:24 UTC, 0zlrlo commented on app/src/main/res/drawable/img_explore_background.png
제가 다시 확인 해 보니 svg 추출이 가능해졌더라구요! 나중에 이런 일이 생기면 그때 알려주신 대처방법을 사용하도록 하겠습니당 감사합니다

2023-05-19 14:00 UTC, b1urrrr commented on app/src/main/res/layout/fragment_explore.xml
> +            app:tabTextAppearance="@style/SubtitleSemibold18"
앗 tabTextAppearance 였군요...ㅎㅎ

2023-05-21 07:37 UTC, b1urrrr commented on app/src/main/res/layout/fragment_explore.xml
> +            android:layout_height="45dp"
> tablayout 자체적으로 높이가 있습니다! 근데 이를 무시하고 원하는 대로 크기를 하고 싶으면 따로 height의 크기를 지정해 주어야 된다는 글을 보아서 높이를 고정적으로 지정했습니다.

안드로이드 기기들은 글씨 크기를 변화시킬 수 있기 때문에 글씨 크기에 따라 탭 크기가 바뀔 수 있도록 padding을 활용하는 것이 더 좋을 것 같은데 어떻게 생각하시나요?

2023-05-21 07:39 UTC, b1urrrr commented on app/src/main/res/drawable/img_explore_background.png
> 제가 다시 확인 해 보니 svg 추출이 가능해졌더라구요! 나중에 이런 일이 생기면 그때 알려주신 대처방법을 사용하도록 하겠습니당 감사합니다

제가 안스로 확인해보니 요 이미지는 벡터처리가 되지 않아서 svg로 추출하면 원래 이미지와 다르게 추출되는 것 같습니다!

2023-05-21 08:02 UTC, 0zlrlo commented on app/src/main/res/layout/fragment_explore.xml
> +            android:layout_height="45dp"
margin을 사용하지 않고 padding을 이용하여 계산해서 만져 보았더니 되었습니다! height는 다시 wrap_content로 바꾸어 놓았습니다.

2023-05-21 08:04 UTC, 0zlrlo commented on app/src/main/res/drawable/img_explore_background.png
아하 그러면 디자이너분들께 요청드리도록 하겠습니다.

2023-05-21 08:40 UTC, DongjooSEO approved these changes
쪼개서 커밋하는 습관 좋아요!@! 저도 앞으로는 이렇게 하겠습니다
일단 approve먼저 할게요!

2023-05-21 08:40 UTC, etama123 commented on app/build.gradle
> +        viewBinding = true
여기에 dataBinding = true 도 들어가야 하지 않나요?

2023-05-21 08:40 UTC, etama123 commented on app/build.gradle
> +        viewBinding = true
엥 위에 들어가있네 중복되는 건 삭제해주세요!

2023-05-21 08:46 UTC, 0zlrlo commented on app/build.gradle
> +        viewBinding = true
옹 3일전에 남겼는데 이게 이제야 뜨네요ㅠㅠ지금 확인했습니다! 당시에는 중복되는 코드가 있었는지 기억이 안 나지만 현재로는 없는 상태입니다! 그래도 알려주셔서 감사합니다:)

2023-05-21 08:56 UTC, b1urrrr approved these changes
코리가 거의 백 개...🤣
다음부터는 좀 자제하겠습니다... 너무 고생하셨어요!!
LGTM 💚

2023-05-21 08:58 UTC, 0zlrlo commented on app/src/main/java/com/release/keyneez/presentation/main/explore/recent/RecentFragment.kt
> +    private lateinit var RecentAdapter: RecentAdapter
넵 감사합니다! 더 신경 써 볼게요:)

2023-05-21 08:58 UTC, 0zlrlo commented on app/src/main/java/com/release/keyneez/presentation/main/explore/recent/RecentViewModel.kt
> +    private fun getRecentItemList() {
넵넵!

2023-05-21 08:59 UTC, merged