[FEAT/#32] search / 검색 뷰 서버 통신 구현
Keyneez/Keyneez-AOS-Release pull request #35
Opened 2023-06-29 14:32 UTC by 0zlrlo

## 관련 이슈
- closed #32

## 작업 내역
- content, user 관련한 기초 세팅 완료하였습니다.
- 검색뷰 서버 붙여 보았습니다.

## PR 포인트
- 아직 서버 배포가 안되어서 서버 잘 붙여진 것만 확인하였습니다.
- 한가지 우려되는 점은 이 브랜치가 좋아요뷰(아직 ui에서 완성되지 않음)에서 파생이 된 브랜치인데 머지를 하면 좋아요뷰는 어떻게 되는 걸까요? 머지를 해도 괜찮나요?

## 실행 화면
<img width="1432" alt="스크린샷 2023-06-29 오후 10 53 57" src="https://github.com/Keyneez/Keyneez-AOS-Release/assets/99941493/0c7e8fd1-6ac4-4501-8389-2ff85587fb8d">

2023-07-01 03:32 UTC, b1urrrr commented
| 한가지 우려되는 점은 이 브랜치가 좋아요뷰(아직 ui에서 완성되지 않음)에서 파생이 된 브랜치인데 머지를 하면 좋아요뷰 작업물도 여기에 쌓이는 것 같은데 맞나요..?

네 같이 쌓일 것 같네여

2023-07-01 05:35 UTC, b1urrrr requested changes
고생하셨습니다~
다음부터 브랜치는 develop에서 파도록 주의해주세요!

2023-07-01 05:35 UTC, b1urrrr commented on app/build.gradle
> +
위에 이미 적용되어 있는 플러그인입니다! 제거해주세요~

2023-07-01 05:35 UTC, b1urrrr commented on app/gradle/wrapper/gradle-wrapper.properties
> +zipStorePath=wrapper/dists
이건 무슨 코드인가요?

2023-07-01 05:35 UTC, b1urrrr commented on app/gradlew
이것도 왜 추가되어야하는지 궁금합니다

2023-07-01 05:35 UTC, b1urrrr commented on app/gradlew.bat
요것두요! 만약 불필요한 파일이면 제거 부탁드립니다

2023-07-01 05:35 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/data/entity/response/ResponseGetContentDto.kt
> +    )
도메인 레이어 안 나누실거면 변수명에서 pk는 빼는 게 작업할 때 더 보기 편하지 않을까요? 다른 파일들도 확인해주세요!

2023-07-01 05:35 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/like/LikeAdapter.kt
> +// 선택한 것 선택 취소한 것 인자로, 뷰홀더 인자에도!
머지하실거면 주석 다 지워주세요!

2023-07-01 05:35 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/like/LikeFragment.kt
> +    }
데이터바인딩 onClick으로 처리 가능한지 한번 확인해주세요

2023-07-01 05:35 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/like/LikeFragment.kt
> +            val removedItems = mutableListOf<Activity>()
새로운 리스트를 생성하는 게 아니라 뷰모델에서 저장된 리스트를 가져오는 게 맞는 것 같습니다
지금은 항상 비워져있는 리스트를 처리하게 설계되어 있네요

2023-07-01 05:35 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/search/SearchActivity.kt
> +    }
success로 바뀔 때마다 호출되는 함수인데, observe를 하는 로직이 들어있으면 안 될 것 같습니다

2023-07-01 05:35 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/util/binding/BindingAdapter.kt
> +    }
이거 필요 없는 거 아닌가요?

2023-07-01 05:35 UTC, b1urrrr commented on app/src/main/res/layout/item_like_content.xml
> +        <import type="android.view.View" />
여기서는 data로 처리를 해야하지 vm 데이터를 연결하면 안 됩니다 제거해주세요

2023-07-01 05:35 UTC, b1urrrr commented on app/src/main/res/layout/item_like_content.xml
> +            isSelected="@{vm.isSelected}"
vm이 아니라 data에 isSelected 변수가 있겠죠?

2023-07-02 04:38 UTC, 0zlrlo commented on app/gradle/wrapper/gradle-wrapper.properties
> +zipStorePath=wrapper/dists
엇 저도 모르겠습니다...실행하다 보니 생겨난 것 같습니다. 삭제할까요?

2023-07-02 04:52 UTC, 0zlrlo commented on app/gradlew
프로젝트에 있는 파일인데, 찾아 보니 빌드시스템을 위한 것이라고 하는데 삭제해도 될까요...?

2023-07-02 05:52 UTC, 0zlrlo commented on app/src/main/res/layout/item_like_content.xml
> +        <import type="android.view.View" />
엇 그러면 해당 콘텐츠를 눌렀을 때 id를 뷰모델에 보내는 것은 어떻게 처리하면 좋을까요? 기존에는 android:onClick="@{() -> vm.setItemsSelected(data.id)}" 이렇게 하였는데 뷰모델과의 연결을 제거하면 fragment_like 파일에서 리사이클러뷰에 이 코드를 작성해야 할까요?

2023-07-02 05:55 UTC, b1urrrr commented on app/src/main/res/layout/item_like_content.xml
> +        <import type="android.view.View" />
전에도 같이 이야기했었던 것 같은데 어댑터 인자로 전달된 함수를 실행시키도록 뷰홀더에 구현해주세용

2023-07-02 05:56 UTC, b1urrrr commented on app/gradlew
빌드할 때 필요한 파일들이면 남겨두는 게 좋을 것 같아요!

2023-07-02 06:38 UTC, 0zlrlo commented on app/src/main/java/com/release/keyneez/presentation/main/search/SearchActivity.kt
> +    }
success로 바뀐다는 것은 서버 통신을 원한다는 것이고, 그러면 검색 결과가 나와야 하기 때문에 success될 때 마다 observe 해야 한다고 생각했습니다. 그런데 이렇게 말씀하신 이유는 함수가 호출될 때마다 중복적으로 관찰이 등록되고 데이터가 변경될 때마다 중복 호출되는 현상이 발생할 수 있기 때문인가요? 만약 여기서 observe가 없어지게 되면 이 파일에서는 observe 코드가 없나요??

2023-07-04 02:00 UTC, DongjooSEO approved these changes
서버 기초 세팅까지,, 
너무 고생하셨습니다🧩

2023-07-04 02:00 UTC, DongjooSEO commented on app/src/main/java/com/release/keyneez/presentation/main/like/LikeFragment.kt
> +class LikeFragment :
해당 프래그먼트에서 바텀네비게이션을 사라지게 해야한다면,
뷰를 그리는 create부분에서 수정하는게 좋을 거 같아요!

2023-07-04 03:29 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/main/search/SearchActivity.kt
> +    }
1. success로 바뀐다는 것은 서버 통신을 원한다는 것이 아니라 서버 통신이 성공적으로 완료되었다는 뜻입니다!
2. observe는 초기 한번만 호출해도 라이브데이터가 바뀔 때마다 관찰이 되기 때문에 불필요하게 중복하여 observe 할 필요가 없습니다.
3. 현재 검색의 state를 observe하고 있기 때문에 서버 통신이 완료된 경우 state 가 success로 바뀌면서 원하는 로직을 실행하도록 구현할 수 있습니다. 그러면 굳이 searchList를 observe할 필요가 없겠죠?

2023-07-04 06:52 UTC, 0zlrlo commented on app/src/main/java/com/release/keyneez/presentation/main/search/SearchActivity.kt
> +    }
헉 아 제가 착각했네요! 이해됐습니다:) 수정해서 올리겠습니다. 감사합니당!

2023-07-06 13:27 UTC, b1urrrr approved these changes
LGTM!!
토스트 커스텀까지...🥺 고생 많으셨습니다!!

2023-07-06 13:28 UTC, merged