Feature/#10 kakao login
Keyneez/Keyneez-AOS-Release pull request #38
Opened 2023-07-08 15:28 UTC by DongjooSEO

## 관련 이슈
- closed #10 

## 작업 내역
- 카카오 로그인 설정
- 온보딩 레이아웃 구현

## PR 포인트
- 온보딩 뷰 레이아웃 내에 있는 버튼 클릭 시에 카카오 로그인 팝업이 뜨도록 했습니다. 
- 개인 정보 설정 뷰 (회원가입 뷰)의 경우 다른 브랜치에서 작업했기 때문에 해당 내용 머지 후에 연결하겠습니다.

## 실행 화면
![image](https://github.com/Keyneez/Keyneez-AOS-Release/assets/83579348/94b3cb7c-01ca-42eb-b5ac-4246c1d6a2be)

2023-07-08 15:38 UTC, 0zlrlo requested changes
고생하셨습니다! 제가 지금 세세하게 보지는 못해서 추후에 확인 후 더 코리 남길게용:) 
앗 그리고 여러 브랜치에서 왔다 갔다 하면서 작업하면 호옥시 브랜치가 꼬일 수 있으니 조심하시길 바래요!
(제가 그럴 뻔 했거등요..)

2023-07-08 15:38 UTC, 0zlrlo commented on app/src/main/res/layout/activity_onboarding.xml
> +            android:paddingVertical="14dp"
텍스트들 모두 다 string에 넣어서 코드 짜주세요!

2023-07-08 15:38 UTC, 0zlrlo commented on app/build.gradle
> +    implementation "com.tbuonomo:dotsindicator:4.3"
이 코드 제가 이미 넣어 놓은 걸로 기억합니다! 확인 후 있다면 빼주세요!

2023-07-08 15:38 UTC, 0zlrlo commented on app/src/main/java/com/release/keyneez/presentation/onboarding/OnboardingActivity.kt
> +    // kakao 로그인 팝업창
기능 구현을 했다면 주석문은 다 빼 주시는 게 좋을 거 같아요

2023-07-08 19:34 UTC, b1urrrr approved these changes
로그인 구현하시느라 고생하셨습니다!!

2023-07-08 19:34 UTC, b1urrrr commented on app/build.gradle
> +        buildConfigField "String", "KAKAO_NATIVE_KEY", kakaoApiKey
base_url과 프로퍼티를 가져오는 방법을 통일시켜주는 것은 어떨가여

2023-07-08 19:34 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/onboarding/OnFirstFragment.kt
> +        fun newInstance() = OnFirstFragment()
companion object 내부 함수는 `@JvmStatic` 추가해주세요!
다른 프래그먼트들도 확인 부탁드립니다

2023-07-08 19:34 UTC, b1urrrr commented on app/src/main/java/com/release/keyneez/presentation/onboarding/OnboardingActivity.kt
> +                when {
error.toString()을 when문 인자로 넣어서 사용하는 게 낫지 않을까요?
로직을 간략화할 수 있는 방법이 뭐가 있을지 생각해봐도 좋을 것 같네용

2023-07-10 10:15 UTC, 0zlrlo approved these changes
고생하셨습니다!

2023-07-10 10:50 UTC, merged